### ISSUE TITLE
Upgrading from 3.90.0 to 3.94.0 breaks timbre output

### ISSUE THREAD

**Issue by ghaskins** [taoensso/encore#72]
After upgrading to Encore 3.94.0, all my timbre 6.5.0 logs started coming out as blank lines. I see there is now a 3.94.1 with a commit that may be related, though it isn't clear. I will try it ASAP.  If this was already addressed, feel free to close this out.

PS: Thanks for all the awesome clojure libs.  I use many of them.

**Comment by ptaoussanis** [comment]
@ghaskins Hi Gregory, really sorry about the trouble! Should be addressed with [v3.96.0](https://github.com/taoensso/encore/releases/tag/v3.96.0), on Clojars now 👍

**Comment by ghaskins** [comment]
3.96.0 fix confirmed.  Thank you!

**Comment by ptaoussanis** [comment]
You're welcome, thanks for the report and confirmation! Much appreciated. Cheers :-)

**Comment by ptaoussanis** [comment]
@ghaskins Hi Gregory, just a heads-up that you'll want to update to Encore [v3.97.0](https://github.com/taoensso/encore/releases/tag/v3.97.0) since [another issue](https://github.com/taoensso/encore/issues/73) came up relating to printing. All the problematic changes have been reverted until I get a chance to re-review everything in more depth.

Again, really sorry about the hassle on this! 🙏

**Comment by ghaskins** [comment]
Thank you!
